### ISSUE TITLE
TypeError: Unexpected keyword arguments: immutable

### ISSUE THREAD

**Issue by smityliu** [ChrisTheCoolHut/Zeratool#12]
(angr) angr@2ecf15fad308:/tmp/Zeratool-master$ python3 zeratool.py challenges/ret -u ctf.hackucf.org -p 9003
[+] Checking pwn type...
[+] Checking for overflow pwn type...
Traceback (most recent call last):
  File "zeratool.py", line 80, in <module>
    main()
  File "zeratool.py", line 38, in main
    properties['pwn_type'] = overflowDetector.checkOverflow(args.file,inputType=properties['input_type'])
  File "/tmp/Zeratool-master/lib/overflowDetector.py", line 34, in checkOverflow
    simgr = p.factory.simgr(state, immutable=False, save_unconstrained=True)
  File "/home/angr/angr-dev/angr/angr/factory.py", line 198, in simgr
    return self.simulation_manager(*args, **kwargs)
  File "/home/angr/angr-dev/angr/angr/factory.py", line 192, in simulation_manager
    return SimulationManager(self.project, active_states=thing, **kwargs)
  File "/home/angr/angr-dev/angr/angr/sim_manager.py", line 108, in __init__
    raise TypeError("Unexpected keyword arguments: " + " ".join(kwargs))
TypeError: Unexpected keyword arguments: immutable

**Comment by docfate111** [comment]
I'm having the same issue

**Comment by a4865g** [comment]
It should be that your angr version is >7.
After I changed to 7, the problem was solved!

**Comment by ChrisTheCoolHut** [comment]
https://github.com/ChrisTheCoolHut/Zeratool/pull/17
