### ISSUE TITLE
r2pipe is no longer supported for python 2

### ISSUE THREAD

**Issue by manishkumarr1017** [ChrisTheCoolHut/Zeratool#14]
I have trouble while installing zeratool . As zeratool uses r2pipe but the latest version of r2pipe is no longer supported for python2
While installing r2pipe 
```
ERROR: Command errored out with exit status 1:
     command: /home/manish/virtualenvs/zeratool/bin/python -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-Rmigan/r2pipe/setup.py'"'"'; __file__='"'"'/tmp/pip-install-Rmigan/r2pipe/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-pip-egg-info-Qp3Wkt
         cwd: /tmp/pip-install-Rmigan/r2pipe/
    Complete output (9 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-Rmigan/r2pipe/setup.py", line 3, in <module>
        import r2pipe
      File "r2pipe/__init__.py", line 38, in <module>
        from r2pipe.open_sync import open
      File "r2pipe/open_sync.py", line 15, in <module>
        from urllib.error import URLError
    ImportError: No module named error
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.

```

So it would be better in install.sh if we specify the r2pipe==1.4.2 as it supports python2 and also the package ropper should installed for the zeratool to work

**Comment by ChrisTheCoolHut** [comment]
https://github.com/ChrisTheCoolHut/Zeratool/pull/17
